[package]
name = "ch5-cpu2"
version = "0.1.0"
authors = ["luke-py-walker <13006398+Luke-Py-Walker@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
